#!/usr/bin/env bash

errors=0
# Ensure changes are committed
git status &>/dev/null
if [[ $? -ne 0 ]]; then
	echo "Error: Make sure working tree is clean before publishing"
	errors=1
fi

if [[ $errors -eq 1 ]]; then
    echo "Aborting due to error"
    exit 1
fi
echo "Publishing..."

echo "Making sure local branch is up to date..."
git pull
git status &>/dev/null
if [[ $? -ne 0 ]]; then
	echo "Error: Fast-Forward failed. Fix any conflicts and publish again"
	exit 1
fi

echo "Creating temporary branch..."
git checkout -b gh-pages

echo "Generating static files..."
python3 freezer.py
if [[ $? -ne 0 ]]; then
	echo "Failed to build, have you setup the environment?"
	echo "Removing temporary branch..."
	git checkout -
	git branch -D gh-pages
	exit 1
fi

echo "Moving static files..."
cp -r website/build/* .
cp -r website/other/* .
